steps:
  # Paso 1: Instalar Python y ejecutar Lint
  - name: "gcr.io/cloud-builders/bash"
    id: Lint
    args:
      - "-c"
      - |
        apt update && apt install -y python3 python3-pip
        pip3 install pylint
        pylint ejemplo-py.py  # Ejecutamos pylint en el archivo ejemplo-py.py

  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/miprimerproyecto-308719/imagenprueba:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/miprimerproyecto-308719/imagenprueba:latest"

images:
  - "gcr.io/miprimerproyecto-308719/imagenprueba:latest"

options:
  logging: CLOUD_LOGGING_ONLY
