steps:
  - name: "gcr.io/cloud-builders/python:3.9"
    id: Lint
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install pylint && pylint ejemplo-py.py  # Ejecutamos pylint en el archivo ejemplo-py.py

  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/miprimerproyecto-308719/imagenprueba:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/miprimerproyecto-308719/imagenprueba:latest"

images:
  - "gcr.io/miprimerproyecto-308719/imagenprueba:latest"

options:
  logging: CLOUD_LOGGING_ONLY
