steps:
  # Paso 1: Ejecutar Lint usando Python 3.9
  - name: "python:3.9"
    id: Lint
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ls -l
        pip install pylint  # Instalamos pylint
        pylint --disable=all ejemplo-py.py  # Ejecutamos pylint sin advertencias

  # Paso 2: Construir la imagen Docker
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/miprimerproyecto-308719/imagenprueba:latest"
      - "."

  # Paso 3: Enviar la imagen al Container Registry
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/miprimerproyecto-308719/imagenprueba:latest"

# Especificamos qué imágenes serán generadas en este pipeline
images:
  - "gcr.io/miprimerproyecto-308719/imagenprueba:latest"

# Opciones adicionales para Cloud Build
options:
  logging: CLOUD_LOGGING_ONLY
