steps:
  # Paso 1: Verificar que el archivo 'ejemplo-py.py' existe antes de ejecutar pylint
  - name: "python:3.9"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ls -lah
        if [ -f "ejemplo_py.py" ]; then
          pip install pylint && pylint ejemplo_py.py
        else
          exit 1
        fi

  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "us-docker.pkg.dev/miprimerproyecto-308719/gcr-repo/imagenprueba:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "us-docker.pkg.dev/miprimerproyecto-308719/gcr-repo/imagenprueba:latest"

images:
  - "us-docker.pkg.dev/miprimerproyecto-308719/gcr-repo/imagenprueba:latest"

options:
  logging: CLOUD_LOGGING_ONLY
